export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';

export const AUTH_LOGOUT_REQUEST = 'AUTH_LOGOUT_REQUEST';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
export const AUTH_LOGOUT_FAILURE = 'AUTH_LOGOUT_FAILURE';

export const ADVERTS_LOADED_SUCCESS ='ADVERTS_LOADED_SUCCESS';
export const ADVERTS_LOADED_FAILURE ='ADVERTS_LOADED_FAILURE';
export const ADVERTS_LOADED_REQUEST ='ADVERTS_LOADED_REQUEST';

export const FILTERS_LOADED_REQUEST = 'FILTERS_LOADED_REQUEST';
export const FILTERS_LOADED_FAILURE = 'FILTERS_LOADED_FAILURE';
export const FILTERS_LOADED_SUCCESS = 'FILTERS_LOADED_SUCCESS';

export const UI_RESET_ERROR= 'UI_RESET_ERROR';